### ISSUE TITLE
Event when other users have entered or left the channel

### ISSUE THREAD

**Issue by Dr-Evans** [Schmoopiie/twitch-irc#26]
Hi @Schmoopiie !

I understand that the join/part events are fired when the client itself joins or leaves a channel. Is there an event that is fired whenever other users join or leave the channel that the client is currently in?

**Comment by Schmoopiie** [comment]
Hello @Dr-Evans,

It is possible to receive the JOINs/PARTs but this is something that will change in the future. The way you receive events in chat depends on your TWITCHCLIENT setting. [Twitch is working on the new IRCv3 tags](http://discuss.dev.twitch.tv/t/irc-v3-the-future/1121) and when it comes out, TWITCHCLIENT will be deprecated. It should still work for a few months but we do not plan to keep this feature in the module; As a matter of fact, we are already supporting IRCv3 tags in the beta version, we are only waiting for Twitch to make it official.

If you still wonder how to receive the JOINs/PARTs, you need to change the [tc option to 1](https://github.com/Schmoopiie/twitch-irc#configuration) in your configuration. Using 1 instead of 3 might result with some events not firing, like timeouts or subscriptions. This is how Twitch chat system is designed.

I recommend the use of the [request module](https://github.com/request/request) and the [undocumented Twitch endpoint](https://tmi.twitch.tv/group/user/lirik/chatters) to retrieve the chatters list of a channel.

Thank you!

**Comment by Dr-Evans** [comment]
Thanks for the quick response!
