### ISSUE TITLE
Is there a good way to output log events to console?

### ISSUE THREAD

**Issue by enilsen16** [Schmoopiie/twitch-irc#27]
Currently all the provided options for logging I could find in the Wiki and in the readme are to a separate log file. Is there a built in way to log all event messages to stdout? 
 
Thanks

edit: Im trying to find a good way to differentiate between when a chat message is a bot command and not?  The best I could figure out so far is -

```
[15:51:04] event - hosting
[15:51:11] event - chat
[15:51:16] event - chat
[15:51:40] event - chat
[15:51:44] event - chat
```

**Comment by Schmoopiie** [comment]
Thank you for posting this, it is not possible with the current version but I guess we could add this feature for the next version. Currently, the debug option shows which event is being fired (hosting 1 time and chat 4 times in your example).

You said you are trying to differentiate between a chat message or a bot command, why not just checking if the first character is "!" in your chat event ?
```javascript
client.addListener('chat', function (channel, user, message) {
    if (message.indexOf('!') === 0) {
        // Might be a command..
        //console.log(message);
        var parts   = message.split(' ');
        var command = parts[0];
        if (command === '!hello') {
            // Do something
        }
    }
});
```

**Comment by enilsen16** [comment]
Thanks @Schmoopiie. If I get a chance I may add a pull request so bot responses are also outputted to console.

**Comment by Schmoopiie** [comment]
Sure thing, PR are welcome! Just make sure you send the PR to the 1.1.1b branch.

Thank you!

**Comment by enilsen16** [comment]
I'm trying to read through your code. Is there an obvious reason as to why the debug isnt catching what the bot responds with? I would think it would console log every chat message it sees in IRC.

**Comment by Schmoopiie** [comment]
Twitch doesn't really follow the IRC Reference, you would need to modify the [socket crlfWrite](https://github.com/Schmoopiie/twitch-irc/blob/master/library/socket.js#L49) which is used to send messages to the server (maybe catch PRIVMSG or something..).

**Comment by Schmoopiie** [comment]
There is a callback for most of the commands in the beta, but it was a pain in the *** to do this with Twitch. Most callbacks are sent 250ms late because it is waiting for the JTV response to the command. There is no callback to the .say command because we can't even see our own message, we can only suppose it was sent. Unless we create another connection but it's not a good idea.

Actually the callback of .say is if you can't say something on a channel (any kind of restrictions), but we cannot catch if our own message was sent properly.

**Comment by Schmoopiie** [comment]
I'm dumb, you can actually catch your own message, make sure the messageFrom is equal to the bot's username in the [_handleMessage](https://github.com/Schmoopiie/twitch-irc/blob/master/library/client.js#L159). Use ``console.log(message);`` and you will see how we receive messages. It wasn't possible before (when it was node-twitch-irc) but now we can.

**Comment by enilsen16** [comment]
That is what I currently do. The problem is if the bots username is also the broadcasters username then all messages are logged to the console. Is there just a way to just console log the message in client.say?

```
/**
 * Say something on a channel.
 *
 * @params {string} channel
 * @params {string} message
 */
client.prototype.say = function say(channel, message, cb) {
    console.log(message);
    if (this.socket !== null) { this.socket.crlfWrite('PRIVMSG ' + Utils.addHash(channel).toLowerCase() + ' :' + message); }
    if (typeof cb === 'function') { setTimeout(function() { CommandError !== '' && cb(CommandError) && cb(null); }, 250); }
};

/**
 * Say something on a channel (action).
 *
 * @params {string} channel
 * @params {string} message
 */
client.prototype.action = function action(channel, message, cb) {
    console.log(message);
    if (this.socket !== null) { this.socket.crlfWrite('PRIVMSG ' + Utils.addHash(channel).toLowerCase() + ' : \x01ACTION ' + message + '\x01'); }
    if (typeof cb === 'function') { setTimeout(function() { CommandError !== '' && cb(CommandError) && cb(null); }, 250); }
};
```

I thought you could something like this but it doesn't follow your templating system. It also might make sense to add response event.

**Comment by enilsen16** [comment]
The code above produces something like this:

```
[12:50:14] raw   - 366: #eyeswl
Hey eyeswl! How you doing? Kappa
[12:51:08] chat  - [#eyeswl] eyeswl: !hello
```

If I just need to get it to follow your templating system and show up in the correct order.

**Comment by Schmoopiie** [comment]
Can you try this update ? I tested it and it works now.. don't forget to add ``debugDetails: true`` in your options.

**Comment by enilsen16** [comment]
Awesome thank you :+1:

**Comment by enilsen16** [comment]
What are you hoping to add in a 1.2 release? If you need any help please let me know.

**Comment by Schmoopiie** [comment]
Right now I am almost done with 1.2.0 .. just waiting for Twitch to make it official with their IRCv3 tags.. I already planned the next version which will offer rates limit support and some kind of a flood protection (an interval for the .say/.action commands) to prevent the bot from spamming.

Anyways, from the changelog: (No links available because I'm not done with the documentation, which will be available on my website instead of GitHub)

## v1.2.0
* Action command to send action messages. (/me &lt;message&gt;)
* Added autoRejoin option to rejoin the exact same channels when reconnected.
* Added a command listener. (might be improved in the next version of twitch-irc)
* Added debugDetails to show additional debug informations.
* Added subanniversay event.
* Added mod and unmod listeners.
* Better handling of Twitch restrictions/limitations.
* Capitalize utils which can also grab the username from the Twitch API for correct capitalization.
* Color command to change the color of the username.
* Commands listener.
* Commands now sends an optional callback.
* Custom logger with timestamp and colors.
* CLI is now available; the module needs to be installed with --global. (we will improve this in the next version of twitch-irc)
* Fixed symbols utils.
* IRCv3 tags support.
* New function .isMod(channel, username) to find out if username is moderator.
* OAuth event listener.
* OAuth hostname can now be changed.
* OAuth redirect after success/failure is now customizable.
* OAuth web template is now customizable.
* Optimized the code.
* Updated the wiki to provide better documentation.
* Removed listeners limit, no more warning.

**Comment by enilsen16** [comment]
:+1:

**Comment by Schmoopiie** [comment]
Don't hesitate to post your ideas here or if you want to contribute to this project you're welcome :smile:

**Comment by enilsen16** [comment]
Will do.
