### ISSUE TITLE
client.part() not firing

### ISSUE THREAD

**Issue by enilsen16** [Schmoopiie/twitch-irc#43]
I call `client.part(user.username);` and no event is fired. I was able to reproduce this in both 1.1.20b and 1.1.19b.

**Comment by enilsen16** [comment]
Looks like it works in master. hm... I'll test with 1.1.18b.

**Comment by Schmoopiie** [comment]
Try the new beta version it should be okay now :smile: 

Thanks!

**Comment by designgears** [comment]
part and join only seem to work if I set the twitch client to 1 in the options.

**Comment by enilsen16** [comment]
are you using the beta or master?

**Comment by designgears** [comment]
I am using the beta.

**Comment by enilsen16** [comment]
Hmmm... I just tried and it works for me. Are you using 1.1.22?

What does your code look like?

**Comment by designgears** [comment]
I am using the example code on the readme with this added... 

```
client.addListener('join', function (channel, username) {
	console.log(username+' joined the channel');
});

client.addListener('part', function (channel, username) {
	console.log(username+' left the channel');
});
```

**Comment by enilsen16** [comment]
Doesn't that listen for a join or part event rather then fire the command? :confused: 

https://github.com/Schmoopiie/twitch-irc/wiki/Command:-Join
https://github.com/Schmoopiie/twitch-irc/wiki/Command:-Part

**Comment by designgears** [comment]
Ah, looks like I mixed up client join/part with users joining/leaving.

**Comment by enilsen16** [comment]
Yep so did I. This may be a separate issue....

**Comment by designgears** [comment]
Looking for users joining/leaving so I can log times.

**Comment by Schmoopiie** [comment]
You would need to set ``tc: 1`` for this but I do not recommend to do it this way if you are doing some kind of a use loyalty system because [Twitch's plan is to deprecate TC (TWITCHCLIENT) and use IRCv3 tags instead](http://discuss.dev.twitch.tv/t/irc-v3-the-future/1121), which doesn't show JOINs and PARTs (yet?). Also, keep in mind that JOINs and PARTs are sent every 30-60secs in batch. I would recommend to use the [request module for node](https://github.com/request/request) instead and query the [Twitch chatters API](https://tmi.twitch.tv/group/user/lirik/chatters) (Undocumented) instead.

**Comment by designgears** [comment]
Thanks Schmoopiie. They have so much undocumented stuff, really frustrating sometimes. :)

I prefer the API chatters list over the part/join, this will work better with what I have planned :+1:
