### ISSUE TITLE
Getting Modlist

### ISSUE THREAD

**Issue by j3ddesign** [Schmoopiie/twitch-irc#45]
I'm currently working on a bot for a friend and I've run into an issue pulling the modlist with client.mods.

It worked previously however it now no longer triggers the mods event. Is there something that has changed with twitch that I need to adjust to accordingly, or Is this a new issue?

Here's the code I'm currently using, triggered on event:join
```javascript
getMods = function(channel) {
    client.mods(channel);
    client.addListener('mods', function (channel, mods) {
    // Do your stuff.
        modlist = mods;
        return;
    });
    return;
};
```

Any help would be awesome :)
Thanks!

**Comment by Dr-Evans** [comment]
Try adding the listener before sending the mods command. Also, this is undocumented but the client actually makes use of [node events](http://nodejs.org/api/events.html) for listeners. As a result, I believe for your use case you should use [once()](http://nodejs.org/api/events.html#events_emitter_once_event_listener) or use addListener once at the beginning when the client is initialized. 

Hope this helps!

**Comment by Schmoopiie** [comment]
Know issue and it was [fixed in the latest beta](https://github.com/Schmoopiie/twitch-irc/commit/5292ccbc071d75c1cfcd67436fc4da9600112587), Twitch is changing a lot of things lately and it is breaking some features.. I will have to release another stable version ASAP I guess..

I recommend to use the user object to check if user is a mod, using the client.mods command makes your client send the /mods command to the channel and you have to make sure you do not exceed 100 messages in 30 seconds (otherwise you will be shadowbanned - 8 hours ban from chat). Using the user object won't send any commands to the server.

Quick example of how to use it:

```javascript
client.addListener('chat', function (channel, user, message) {
    if (user.special.indexOf('mod') >= 0) {
        // User is a mod..
    }
});
```

Check the user [documentation here](https://github.com/Schmoopiie/twitch-irc/wiki/User-object).
